### ISSUE TITLE
Mokapot and percolator error MSfragger pepxml.

### ISSUE THREAD

**Issue by Skourtis** [wilhelm-lab/oktoberfest#131]
Hi, 

I'm reanalysing some publically available SILAC data with MSfragger . The files I'm analysing are the 3 .raw files of PXD032200 with 100% FDR. 

I am using this config file and have installed both mono, percolator v3.5 and have themoparser on my linux device. 
here is the log from the percolator and mokapot run, as well as the pepxml input file. 

I'm not sure what's going wrong.

Thanks,
Savvas
[160915_BSchrul_Kopito_5978_ILIC_04_SILAC_rerun.zip](https://github.com/wilhelm-lab/oktoberfest/files/12740535/160915_BSchrul_Kopito_5978_ILIC_04_SILAC_rerun.zip)
[mokapot_log.txt](https://github.com/wilhelm-lab/oktoberfest/files/12740567/mokapot_log.txt)

[test_thp1_config.zip](https://github.com/wilhelm-lab/oktoberfest/files/12740544/test_thp1_config.zip)
[percolator_log.txt](https://github.com/wilhelm-lab/oktoberfest/files/12740543/percolator_log.txt)

**Comment by picciama** [comment]
Hello Savvas, it seems that there aren't any targets below the FDR filter, which is why mokapot then simply fails. We observed this a few times as well, especially when the dataset is small and the quality is not that high. This is indicated by the LDA analysis prior to percolator/mokapot cannot find any target candidates below an FDR of 0.01 and 0.02. Percolator is a bit better in this regard but in order to tell more, I will need to see the log file from your percolator run, i.e. the log file percolator produces itself, which is located in your output folder/results/percolator. There should be original / rescore.log 
I will have to rerun this data myself though and maybe get some more people involved to investigate this further.

**Comment by Skourtis** [comment]
Hi Mario!

Thanks for getting back to me. I'm surprised by percolator's inability to find targets under FDR 0.01 and 0.02 because when I run percolator through MSfragger (without Msbooster enabled), it finds quite a lot of targets which it then scores. in theory the fragpipe-integrated percolator is reading the same pepXML as oktoberfest.

Here I'm including an example with a single .raw file from PXD032200 (160915_BSchrul_Kopito_5978_ILIC_04_SILAC_rerun.raw), with the MSfragger/Fragpipe configuration parameters and the fragpipe-percolator target/decoys output which finds targets under FDR 0.01. 

Also including the oktoberfest config and oktoberfest-percolator log file. 

https://crgcnag-my.sharepoint.com/:u:/g/personal/skourtis_crg_es/EW0yuQCCAQZNrBRzEdCex6oBde1bWoAk_yf-oeuK3gaoPQ?e=HxojGk

Why do you think this is failing? Thanks!
Savvas

**Comment by picciama** [comment]
Hi @Skourtis , sorry for my late reply, I was busy fixing bugs that also had to do with this issue. I was able to run your data by fixing a few things:
1. The file seems to be CID data, therefore, you should use the prosit model `Prosit_2020_intensity_CID`, which is specially trained for this dissociation method.
2. Your config uses 20 ppm mass tolerance for annotation of spectra, which does not seem to work here because the data is acquired using an ion trap. According to https://www.ebi.ac.uk/pride/archive/projects/PXD032200, processing was done with a tolerance of 0.4 Da, which is why you need to change this in the config as well.
3. Since you uploaded this issue, I was looking into a few other bugs that caused problems. I tested your data with my development versions and the newest percolator version 3.06.1 which fixes some bugs on their end.

This is the configuration you should use for this data:
```
{
    "type": "Rescoring",
    "tag": "",
    "allFeatures": false,
    "inputs": {
        "search_results": "./",
        "search_results_type": "Msfragger",
        "spectra": "./",
        "spectra_type": "raw"
    },
    "models": {
        "intensity": "Prosit_2020_intensity_CID",
        "irt": "Prosit_2019_irt"
    },
    "output": "./out",
    "outputFormat": "",
    "prediction_server": "koina.proteomicsdb.org:443",
    "ssl": true,
    "numThreads": 3,
    "fdr_estimation_method": "percolator",
    "regressionMethod": "spline",
    "thermoExe": "/opt/compomics/ThermoRawFileParser.exe",
    "massTolerance": .4,
    "unitMassTolerance": "da"
}
```

These are the gains I managed to get using percolator (peptide level left, PSM level right): 
![image](https://github.com/wilhelm-lab/oktoberfest/assets/50995210/4902f88a-6622-42af-8b76-486c7a60201d)

And this is the percolator score distribution for targets and peptides when using the MsFragger score with percolator (x-axis) versus Prosit derived scores (y-axis).
![image](https://github.com/wilhelm-lab/oktoberfest/assets/50995210/10f406cc-d825-4cd4-93f7-5fc054ab906b)

The 1%FDR cutoff is at a percolator score of zero and you can see that target and decoy score distributions are nicely separated around that value over the y-axis. Therefore, rescoring with Prosit definitely works for this dataset.

I plan to release oktoberfest 0.5.1 this week but I have to add compatibility for a change in the koina prediction server. I will inform you here once I am done.
