### ISSUE TITLE
Allow spaces in raw file names

### ISSUE THREAD

**Issue by MatthewThe** [wilhelm-lab/oktoberfest#18]
**Describe the bug**

Whenever a raw file contains a space, the RAW to mzML conversion fails because the argument does not get escaped properly.

**To Reproduce**

1. Run oktoberfest with a raw file with a space in the name

**System:**

-   Docker image

**Comment by picciama** [comment]
This is not an issue in oktoberfest but in spectrum_io. I opened an issue: https://github.com/wilhelm-lab/spectrum_io/issues/25

**Comment by picciama** [comment]
I have created a PR in spectrum_io that fixes this problem: https://github.com/wilhelm-lab/spectrum_io/pull/26
However, this will break oktoberfest since the order of arguments has changed when calling the function from oktoberfest. 
I will switch to kwargs in the call in oktoberfest now to make it work and be backwards compatible for this to be fixed.
