### ISSUE TITLE
Errors occurring during all jobs.

### ISSUE THREAD

**Issue by karimwh** [wilhelm-lab/oktoberfest#62]
[Oktoberfest.zip](https://github.com/wilhelm-lab/oktoberfest/files/11319928/Oktoberfest.zip)

I tried pulling the last version of Oktoberfest, but it didn't work.

**Comment by picciama** [comment]
@karimwh closing this as it has been fixed by releasing version 0.3.1 of spectrum_fundamentals and the current version of oktoberfest development where an error from the grpc prediction server is properly shown (0619b6eb69f20786d8f71a3a91a7045941a48f08), dependencies are fixed (1de7eeb873d16b15ec75ff83fc09695be91f491e) and the paths in the tutorial notebooks are corrected (4bd05eef906e82d50aee42e37212a19fdd0f4333)
